version: 2
updates:
- package-ecosystem: composer
  directory: "/src/lib"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: egulias/email-validator
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: filp/whoops
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
  - dependency-name: voku/anti-xss
    versions:
    - 4.1.32
