<?php
/**
 * write_web_config()
 *
 * Writes IIS web.config file with URL rewrite rules.
 *
 * @category function
 * @author M.Noermoehammad
 * @license MIT
 * @version 1.0
 * @param string $permalink_status
 * @param string $user_level
 * @param string $data
 *
 */
function write_web_config($permalink_status, $user_level, $data)
{

    clearstatcache();

    $privilege = user_privilege();

    if ($privilege === 'administrator' || $privilege === 'manager') {
        $file_path = dirname(__FILE__, 3) . '/web.config';

        $fp = fopen($file_path, 'w');

        if ($fp) {
            fwrite($fp, $data);
            fclose($fp);
        } else {
            scriptlog_error("Cannot open file for writing: " . $file_path);
        }
    } else {
        scriptlog_error("Insufficient privileges to write IIS web.config.");
    }
}

/**
 * read_web_config_template()
 *
 * Generates IIS web.config-compatible rewrite rules for ScriptLog routes.
 *
 * @category function
 * @author M.Noermoehammad
 * @license MIT
 * @version 1.0
 * @param string $permalink_status
 * @return string
 *
 */
function read_web_config_template($permalink_status)
{

    $content = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
    $content .= '<configuration>' . "\n";
    $content .= '    <system.webServer>' . "\n";
    $content .= '        <!-- Auto-generated by ScriptLog. Do not edit manually. -->' . "\n";

    if ($permalink_status === 'yes') {
        $content .= '        <rewrite>' . "\n";
        $content .= '            <rules>' . "\n";
        $content .= '                <!-- API routes -->' . "\n";
        $content .= '                <rule name="API Routes" stopProcessing="true">' . "\n";
        $content .= '                    <match url="^api/(.*)$" />' . "\n";
        $content .= '                    <action type="Rewrite" url="api/index.php" />' . "\n";
        $content .= '                </rule>' . "\n";
        $content .= '                <!-- Public asset files -->' . "\n";
        $content .= '                <rule name="Public Assets" stopProcessing="true">' . "\n";
        $content .= '                    <match url="^public/.*\.(ico|css|png|jpg|jpeg|webp|gif|js|txt|htm|html|eot|svg|ttf|woff|woff2|webm|ogg|mp4|wav|mp3|pdf)$" />' . "\n";
        $content .= '                    <action type="None" />' . "\n";
        $content .= '                </rule>' . "\n";
        $content .= '                <!-- Language prefix routes -->' . "\n";
        $content .= '                <rule name="Language Routes" stopProcessing="true">' . "\n";
        $content .= '                    <match url="^[a-z]{2}/(post|page|blog|category|archive|archives|tag|privacy|download|download_file)(/.*)?$" />' . "\n";
        $content .= '                    <action type="Rewrite" url="index.php" />' . "\n";
        $content .= '                </rule>' . "\n";
        $content .= '                <rule name="Language Root" stopProcessing="true">' . "\n";
        $content .= '                    <match url="^[a-z]{2}/?$" />' . "\n";
        $content .= '                    <action type="Rewrite" url="index.php" />' . "\n";
        $content .= '                </rule>' . "\n";
        $content .= '                <!-- Application URL rewriting -->' . "\n";
        $content .= '                <rule name="ScriptLog Rewrite" stopProcessing="true">' . "\n";
        $content .= '                    <match url="^(post|page|blog|category|archive|archives|tag|privacy|download|download_file)(/.*)?$" />' . "\n";
        $content .= '                    <action type="Rewrite" url="index.php" />' . "\n";
        $content .= '                </rule>' . "\n";
        $content .= '                <!-- Root request -->' . "\n";
        $content .= '                <rule name="Root Request" stopProcessing="true">' . "\n";
        $content .= '                    <match url="^$" />' . "\n";
        $content .= '                    <action type="Rewrite" url="index.php" />' . "\n";
        $content .= '                </rule>' . "\n";
        $content .= '            </rules>' . "\n";
        $content .= '        </rewrite>' . "\n";
    } else {
        $content .= '        <!-- Permalink disabled - route all requests to index.php -->' . "\n";
        $content .= '        <rewrite>' . "\n";
        $content .= '            <rules>' . "\n";
        $content .= '                <rule name="Catch-All" stopProcessing="true">' . "\n";
        $content .= '                    <match url=".*" />' . "\n";
        $content .= '                    <conditions>' . "\n";
        $content .= '                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />' . "\n";
        $content .= '                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />' . "\n";
        $content .= '                    </conditions>' . "\n";
        $content .= '                    <action type="Rewrite" url="index.php" />' . "\n";
        $content .= '                </rule>' . "\n";
        $content .= '            </rules>' . "\n";
        $content .= '        </rewrite>' . "\n";
    }

    $content .= '    </system.webServer>' . "\n";
    $content .= '</configuration>' . "\n";

    return $content;
}
