<?php

/**
 * write_nginx_config()
 *
 * Writes Nginx rewrite rules to a local file that can be included in Nginx config.
 * For use with CloudPanel or manual Nginx setups.
 *
 * @category function
 * @author M.Noermoehammad
 * @license MIT
 * @version 1.0
 * @param string $permalink_status
 * @param string $user_level
 * @param string $data
 *
 */
function write_nginx_config($permalink_status, $user_level, $data)
{

    clearstatcache();

    $privilege = (isset($user_level)) ? user_privilege() : "";

    if ($privilege === 'administrator' || $privilege === 'manager') {
        $file_path = dirname(__FILE__, 3) . '/nginx-rewrites.conf';

        $fp = fopen($file_path, 'w');

        if ($fp) {
            fwrite($fp, $data);
            fclose($fp);
        } else {
            scriptlog_error("Cannot open file for writing: " . $file_path);
        }
    } else {
        scriptlog_error("Insufficient privileges to write Nginx config.");
    }
}

/**
 * read_nginx_config_template()
 *
 * Generates Nginx-compatible rewrite rules for ScriptLog routes.
 *
 * @category function
 * @author M.Noermoehammad
 * @license MIT
 * @version 1.0
 * @param string $permalink_status
 * @return string
 *
 */
function read_nginx_config_template($permalink_status)
{

    $content  = '# START ScriptLog Nginx Rewrites' . PHP_EOL;
    $content .= '# This file is auto-generated by ScriptLog. Do not edit manually.' . PHP_EOL;
    $content .= '# Include this file in your Nginx server block or vhost config:' . PHP_EOL;
    $content .= '#   include /path/to/nginx-rewrites.conf;' . PHP_EOL . PHP_EOL;

    if ($permalink_status === 'yes') {
        # Handle API routes (highest priority)
        $content .= '# API routes' . PHP_EOL;
        $content .= 'location ~ ^/api/ {' . PHP_EOL;
        $content .= '    try_files $uri $uri/ /api/index.php?$query_string;' . PHP_EOL;
        $content .= '}' . PHP_EOL . PHP_EOL;

        # Handle root and known application prefixes
        $content .= '# Main application routes' . PHP_EOL;
        $content .= 'location / {' . PHP_EOL;
        $content .= '    try_files $uri $uri/ /index.php?$query_string;' . PHP_EOL;
        $content .= '}' . PHP_EOL . PHP_EOL;

        # Handle language-based routing (e.g., /en/post/..., /ar/blog/...)
        $content .= '# Language prefix routing' . PHP_EOL;
        $content .= 'location ~ ^/[a-z]{2}/ {' . PHP_EOL;
        $content .= '    try_files $uri $uri/ /index.php?$query_string;' . PHP_EOL;
        $content .= '}' . PHP_EOL . PHP_EOL;

        # Deny access to sensitive files
        $content .= '# Deny access to sensitive files' . PHP_EOL;
        $content .= 'location ~ /\.(htaccess|htpasswd|git|env|config) {' . PHP_EOL;
        $content .= '    deny all;' . PHP_EOL;
        $content .= '}' . PHP_EOL . PHP_EOL;

        $content .= 'location ~* \.(ini|log|db|sql)$ {' . PHP_EOL;
        $content .= '    deny all;' . PHP_EOL;
        $content .= '}' . PHP_EOL . PHP_EOL;
    } else {
        # When permalinks are disabled, all requests go to index.php
        $content .= '# Permalink disabled - route all requests to index.php' . PHP_EOL;
        $content .= 'location / {' . PHP_EOL;
        $content .= '    try_files $uri $uri/ /index.php?$query_string;' . PHP_EOL;
        $content .= '}' . PHP_EOL . PHP_EOL;
    }

    $content .= '# FINISH ScriptLog Nginx Rewrites' . PHP_EOL;

    return $content;
}

/**
 * get_webserver_config_filename()
 *
 * Returns the appropriate config filename based on web server.
 *
 * @category function
 * @author M.Noermoehammad
 * @license MIT
 * @version 1.0
 * @param string $server_type
 * @return string
 *
 */
function get_webserver_config_filename($server_type)
{

    switch ($server_type) {
        case 'Nginx':
            return 'nginx-rewrites.conf';
        case 'Apache':
        case 'LiteSpeed':
            return '.htaccess';
        default:
            return '.htaccess';
    }
}
