<?php
/**
 * Utility Manifest Generator
 * Scans the utility directory and regenerates the utility-loader.php file.
 * This tool should be run whenever a new utility file is added to /lib/utility/.
 * Usage: php generate-utility-list.php
 * 
 * @category Scan utility directory then regenerates the utility-loader.php file
 * @author  M.Noermoehammad
 * @license MIT
 */

// Define the path to the utility folder and the target output file
$utility_dir = __DIR__ . '/lib/utility/';
$output_file = __DIR__ . '/lib/utility-loader.php';

// Use glob() to quickly find all PHP files (this runs ONLY when you execute this script)
$files = glob($utility_dir . '*.php');

// Extract just the filenames (e.g., 'sanitization.php')
$utility_files = array_map('basename', $files);

// Define the content for the utility-loader.php file
$php_content = "<?php\n";
$php_content .= "/**\n * GENERATED UTILITY LOADER FILE.\n * DO NOT EDIT THIS FILE MANUALLY.\n * Run 'php generate-utility-list.php' to regenerate this list.\n */\n\n";

// Wrap function declaration to prevent duplicate function errors
$php_content .= "if (!function_exists('load_core_utilities')) {\n";
$php_content .= "    function load_core_utilities()\n";
$php_content .= "    {\n";

// Start the array list
$php_content .= "        \$utility_files = [\n";

// Add each file to the array list
foreach ($utility_files as $file) {
    $php_content .= "        '" . $file . "',\n";
}

$php_content .= "    ];\n\n";

$php_content .= "        \$utility_dir = __DIR__ . DIRECTORY_SEPARATOR . 'utility' . DIRECTORY_SEPARATOR;\n";
$php_content .= "        foreach (\$utility_files as \$file) {\n";
$php_content .= "            require_once \$utility_dir . \$file;\n";
$php_content .= "        }\n";
$php_content .= "    }\n";
$php_content .= "}\n\n";

// Add guard to prevent calling before function is defined
$php_content .= "if (!function_exists('load_core_utilities')) {\n";
$php_content .= "    load_core_utilities();\n";
$php_content .= "}\n";

// Write the content to the target file
if (file_put_contents($output_file, $php_content) !== false) {
    echo "Successfully generated and updated: " . $output_file . "\n";
    echo "Total files listed: " . count($utility_files) . "\n";
} else {
    echo "ERROR: Could not write to " . $output_file . ". Check file permissions.\n";
}
