<?php

use PHPUnit\Framework\TestCase;

class NginxConfigWriterTest extends TestCase
{
    private string $utilityPath;

    protected function setUp(): void
    {
        parent::setUp();
        $this->utilityPath = __DIR__ . '/../../src/lib/utility/write-nginx-config.php';

        if (!function_exists('read_nginx_config_template')) {
            require_once $this->utilityPath;
        }
    }

    public function testReadNginxConfigTemplateFunctionExists(): void
    {
        $this->assertTrue(function_exists('read_nginx_config_template'));
    }

    public function testWriteNginxConfigFunctionExists(): void
    {
        $this->assertTrue(function_exists('write_nginx_config'));
    }

    public function testGetWebserverConfigFilenameFunctionExists(): void
    {
        $this->assertTrue(function_exists('get_webserver_config_filename'));
    }

    public function testSourceFileIsValidPhpSyntax(): void
    {
        $output = [];
        $returnCode = 0;
        exec('php -l ' . escapeshellarg($this->utilityPath) . ' 2>&1', $output, $returnCode);
        $this->assertEquals(0, $returnCode, 'PHP syntax check failed: ' . implode("\n", $output));
    }

    public function testReadNginxConfigTemplateReturnsString(): void
    {
        $result = read_nginx_config_template('yes');
        $this->assertIsString($result);
    }

    public function testReadNginxConfigTemplateWithPermalinksEnabled(): void
    {
        $result = read_nginx_config_template('yes');
        $this->assertStringContainsString('ScriptLog Nginx Rewrites', $result);
        $this->assertStringContainsString('location ~ ^/api/', $result);
        $this->assertStringContainsString('location /', $result);
        $this->assertStringContainsString('location ~ ^/[a-z]{2}/', $result);
        $this->assertStringContainsString('deny all', $result);
    }

    public function testReadNginxConfigTemplateWithPermalinksDisabled(): void
    {
        $result = read_nginx_config_template('no');
        $this->assertStringContainsString('ScriptLog Nginx Rewrites', $result);
        $this->assertStringContainsString('Permalink disabled', $result);
        $this->assertStringContainsString('try_files $uri $uri/ /index.php?$query_string;', $result);
        $this->assertStringNotContainsString('location ~ ^/api/', $result);
    }

    public function testReadNginxConfigTemplateStartsWithComment(): void
    {
        $result = read_nginx_config_template('yes');
        $this->assertStringStartsWith('# START ScriptLog Nginx Rewrites', $result);
    }

    public function testReadNginxConfigTemplateEndsWithFinish(): void
    {
        $result = read_nginx_config_template('yes');
        $this->assertStringEndsWith('# FINISH ScriptLog Nginx Rewrites' . PHP_EOL, $result);
    }

    public function testGetWebserverConfigFilenameReturnsNginxConf(): void
    {
        $this->assertEquals('nginx-rewrites.conf', get_webserver_config_filename('Nginx'));
    }

    public function testGetWebserverConfigFilenameReturnsHtaccessForApache(): void
    {
        $this->assertEquals('.htaccess', get_webserver_config_filename('Apache'));
    }

    public function testGetWebserverConfigFilenameReturnsHtaccessForLiteSpeed(): void
    {
        $this->assertEquals('.htaccess', get_webserver_config_filename('LiteSpeed'));
    }

    public function testGetWebserverConfigFilenameReturnsWebConfigForMicrosoftIis(): void
    {
        $this->assertEquals('web.config', get_webserver_config_filename('Microsoft-IIS'));
    }

    public function testGetWebserverConfigFilenameReturnsWebConfigForIis(): void
    {
        $this->assertEquals('web.config', get_webserver_config_filename('IIS'));
    }

    public function testGetWebserverConfigFilenameDefaultIsHtaccess(): void
    {
        $this->assertEquals('.htaccess', get_webserver_config_filename('Unknown'));
    }

    public function testGetWebserverConfigFilenameReturnsString(): void
    {
        $this->assertIsString(get_webserver_config_filename('Nginx'));
    }

    public function testReadNginxConfigTemplateHasReturnAnnotation(): void
    {
        $source = file_get_contents($this->utilityPath);
        $this->assertStringContainsString('@return string', $source);
    }

    public function testGetWebserverConfigFilenameHasReturnAnnotation(): void
    {
        $source = file_get_contents($this->utilityPath);
        $this->assertStringContainsString('@return string', $source);
    }

    public function testReadNginxConfigTemplateWithPermalinksDisabledDoesNotContainDenyRules(): void
    {
        $result = read_nginx_config_template('no');
        $this->assertStringNotContainsString('deny all', $result);
        $this->assertStringNotContainsString('location ~ ^/api/', $result);
    }

    public function testReadNginxConfigTemplateContainsAutoGeneratedWarning(): void
    {
        $result = read_nginx_config_template('yes');
        $this->assertStringContainsString('This file is auto-generated by ScriptLog', $result);
    }
}
