<?php

use PHPUnit\Framework\TestCase;

class WebConfigWriterTest extends TestCase
{
    private string $utilityPath;

    protected function setUp(): void
    {
        parent::setUp();
        $this->utilityPath = __DIR__ . '/../../src/lib/utility/write-web-config.php';

        if (!function_exists('read_web_config_template')) {
            require_once $this->utilityPath;
        }
    }

    public function testReadWebConfigTemplateFunctionExists(): void
    {
        $this->assertTrue(function_exists('read_web_config_template'));
    }

    public function testWriteWebConfigFunctionExists(): void
    {
        $this->assertTrue(function_exists('write_web_config'));
    }

    public function testSourceFileIsValidPhpSyntax(): void
    {
        $output = [];
        $returnCode = 0;
        exec('php -l ' . escapeshellarg($this->utilityPath) . ' 2>&1', $output, $returnCode);
        $this->assertEquals(0, $returnCode, 'PHP syntax check failed: ' . implode("\n", $output));
    }

    public function testReadWebConfigTemplateReturnsString(): void
    {
        $result = read_web_config_template('yes');
        $this->assertIsString($result);
    }

    public function testReadWebConfigTemplateWithPermalinksEnabled(): void
    {
        $result = read_web_config_template('yes');
        $this->assertStringContainsString('<?xml version="1.0" encoding="UTF-8"?>', $result);
        $this->assertStringContainsString('<configuration>', $result);
        $this->assertStringContainsString('<system.webServer>', $result);
        $this->assertStringContainsString('<rewrite>', $result);
        $this->assertStringContainsString('<rules>', $result);
        $this->assertStringContainsString('API Routes', $result);
        $this->assertStringContainsString('Language Routes', $result);
        $this->assertStringContainsString('ScriptLog Rewrite', $result);
    }

    public function testReadWebConfigTemplateWithPermalinksDisabled(): void
    {
        $result = read_web_config_template('no');
        $this->assertStringContainsString('<?xml version="1.0" encoding="UTF-8"?>', $result);
        $this->assertStringContainsString('Permalink disabled', $result);
        $this->assertStringContainsString('<rule name="Catch-All"', $result);
        $this->assertStringNotContainsString('API Routes', $result);
        $this->assertStringNotContainsString('Language Routes', $result);
    }

    public function testReadWebConfigTemplateStartsWithXmlDeclaration(): void
    {
        $result = read_web_config_template('yes');
        $this->assertStringStartsWith('<?xml version="1.0" encoding="UTF-8"?>', $result);
    }

    public function testReadWebConfigTemplateEndsWithConfigurationClose(): void
    {
        $result = read_web_config_template('yes');
        $this->assertStringEndsWith('</configuration>' . "\n", $result);
    }

    public function testReadWebConfigTemplateContainsAutoGeneratedComment(): void
    {
        $result = read_web_config_template('yes');
        $this->assertStringContainsString('Auto-generated by ScriptLog', $result);
    }

    public function testReadWebConfigTemplateWithPermalinksEnabledHasPublicAssetsRule(): void
    {
        $result = read_web_config_template('yes');
        $this->assertStringContainsString('Public Assets', $result);
        $this->assertStringContainsString('css', $result);
        $this->assertStringContainsString('js', $result);
    }

    public function testReadWebConfigTemplateWithPermalinksEnabledHasRootRequestRule(): void
    {
        $result = read_web_config_template('yes');
        $this->assertStringContainsString('Root Request', $result);
        $this->assertStringContainsString('url="^$"', $result);
    }

    public function testWriteWebConfigFunctionHasDocBlock(): void
    {
        $source = file_get_contents($this->utilityPath);
        $this->assertStringContainsString('@param string $permalink_status', $source);
        $this->assertStringContainsString('@param string $user_level', $source);
        $this->assertStringContainsString('@param string $data', $source);
    }

    public function testReadWebConfigTemplateFunctionHasReturnAnnotation(): void
    {
        $source = file_get_contents($this->utilityPath);
        $this->assertStringContainsString('@return string', $source);
    }
}
